### ISSUE TITLE
ERROR: Error from foobar2000.foobar2000.on_execute

### ISSUE THREAD

**Issue by hced** [tuteken/Keypirinha-Plugin-foobar2000#1]
I get the following error:
```
17:45:39.790 ** ERROR: Error from foobar2000.foobar2000.on_execute: <class 'OSError'>: [WinError 87] Felaktig parameter
Traceback (most recent call last):
  File "C:\Program Files\Keypirinha\portable\Profile\InstalledPackages\foobar2000.keypirinha-package\foobar2000.py", line 68, in on_execute
  File "lib\subprocess.py", line 267, in call
  File "lib\subprocess.py", line 709, in __init__
  File "lib\subprocess.py", line 997, in _execute_child
```
I have a portable foobar2000 installation as defined in my `foobar2000.ini`:
```
[main]
    file_path = "C:\\Portable\\foobar2000\\foobar2000.exe"
```

### EDIT
If I try this in `foobar2000.ini` (same result with single `\` or double `\\` backslashes):
```
[main]
    file_path = C:\Portable\foobar2000\
```
… I get a permissions error:
```
18:09:26.449 ** ERROR: Error from foobar2000.foobar2000.on_execute: <class 'PermissionError'>: [WinError 5] Permission denied
Traceback (most recent call last):
  File "C:\Program Files\Keypirinha\portable\Profile\InstalledPackages\foobar2000.keypirinha-package\foobar2000.py", line 68, in on_execute
  File "lib\subprocess.py", line 267, in call
  File "lib\subprocess.py", line 709, in __init__
  File "lib\subprocess.py", line 997, in _execute_child
```

**Comment by tuteken** [comment]
Thank you for reporting this issue.  My apologies for the slow reply.  I have merged a fix into the master code branch.  You will need to reinstall the package and then it should start working for you.
